title: Will hack for coffee
author: lolkatz
description: "Hack for good and protect the internet"

# social links
twitter_username: 0xfil # DO NOT include the @ character, or else the build will fail!
github_username:  lolkatz # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

---
layout: default
comments: true
# other options
---
